### ISSUE TITLE
hook is not defind

### ISSUE THREAD

**Issue by kang204** [CC11001100/ast-hook-for-js-RE#49]
我在src/proxy-server目录下运行过 在最外层src也运行过 一直是hook 未定义

**Comment by madking177** [comment]
我也是这个情况

**Comment by madking177** [comment]
你在src上一级别目录运行 就好了

**Comment by 13426867603** [comment]
![Snipaste_2024-08-21_17-11-12](https://github.com/user-attachments/assets/d3647cd0-424d-4910-8b36-198ac3d7f4b5)
新更新的版本，hook.js路径不对，可以自己改一下，如果不会改，可以使用旧版本。

**Comment by 8384626** [comment]
![image](https://github.com/user-attachments/assets/f721f169-df6c-46d9-9d9f-bcf8479bddcf)
改成了正确路径也不可以

**Comment by 8384626** [comment]
> ![image](https://private-user-images.githubusercontent.com/70519610/360472156-f721f169-df6c-46d9-9d9f-bcf8479bddcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzg4MzIsIm5iZiI6MTcyNDMzODUzMiwicGF0aCI6Ii83MDUxOTYxMC8zNjA0NzIxNTYtZjcyMWYxNjktZGY2Yy00NmQ5LTlkOWYtYmNmODQ3OWJkZGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0NTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OGI2ZjZjYjhmMTYwMGZkZTU0Yzk2ZDM4ZjI3MzAzN2RjOWQ0OTc3ZjhhNzA0OWU1N2Q5YjRmOGY1ZTRlODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KaIV1Vr9a4Mby-vUFSK9agHdZTBjNbqgxGGuyExfhAM) 改成了正确路径也不可以

已解决
