### ISSUE TITLE
大佬您好，我使用的是最新版的，有时候无法调出hook.js，我看了日志如下：

### ISSUE THREAD

**Issue by chsyts** [CC11001100/ast-hook-for-js-RE#51]
**Describe the bug**
    at createPromise (D:\Tools\ast-hook-for-js-RE-master\node_modules\co\index.js:30:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\Tools\ast-hook-for-js-RE-master\\src\\proxy-server\\src\\components\\global-assign-hook-component\\core\\hook.js'
}
[AnyPr
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
浏览器是360极速浏览器

**Comment by yanghongm** [comment]
同样的问题，看样子是路径的问题

**Comment by yanghongm** [comment]
在最上面的目录下面运行node src/proxy-server/proxy-server.js就好了

**Comment by songzhibin97** [comment]
#49
